### ISSUE TITLE
Rails 5.2: Passing a class to the class_name

### ISSUE THREAD

**Issue by jonhue** [mbleigh/acts-as-taggable-on#814] opened 2017-03-10 20:31 UTC
> DEPRECATION WARNING: Passing a class to the `class_name` is deprecated and will raise an ArgumentError in Rails 5.2. It eagerloads more classes than necessary and potentially creates circular dependencies. Please pass the class name as a string: `has_many :tag_taggings, class_name: 'ActsAsTaggableOn::Tagging'` (called from <class:User> at c:/Users/Jonas/gitapps/slooob/app/models/user.rb:16)
DEPRECATION WARNING: Passing a class to the `class_name` is deprecated and will raise an ArgumentError in Rails 5.2. It eagerloads more classes than necessary and potentially creates circular dependencies. Please pass the class name as a string: `has_many :tags, class_name: 'ActsAsTaggableOn::Tag'` (called from <class:User> at c:/Users/Jonas/gitapps/slooob/app/models/user.rb:16)

**Comment by tirdadc** [comment] 2017-03-12 17:33
Duplicate of https://github.com/mbleigh/acts-as-taggable-on/issues/807

**Closed** 2017-03-12 18:53 UTC

**Comment by glendel** [comment] 2018-05-31 12:54
Please go to here : [Pull Request #887](https://github.com/mbleigh/acts-as-taggable-on/pull/887) to see all the ready to merge and to use solutions to work with Rails 5.2! It is fully tested and ready to go! It is just missing to merge the changes into the main project!
